/* config.h for bundled editline - hand-written for Unix (macOS/Linux).
 * Generated by autoconf when building from the full editline distribution;
 * we provide a static version here so no autoconf run is needed.
 * Version: editline 1.17.1 (https://github.com/troglobit/editline)
 */
#ifndef EDITLINE_CONFIG_H_
#define EDITLINE_CONFIG_H_

#define SYS_UNIX 1

/* Standard headers available on macOS and Linux */
#define HAVE_DIRENT_H   1
#define HAVE_SIGNAL_H   1
#define HAVE_STDLIB_H   1
#define HAVE_STRING_H   1
#define HAVE_TERMIOS_H  1
#define HAVE_UNISTD_H   1

/* Standard functions available on macOS and Linux */
#define HAVE_STRCHR     1
#define HAVE_STRDUP     1
#define HAVE_STRRCHR    1
#define HAVE_TCGETATTR  1
#define HAVE_PERROR     1

/* Features we want enabled */
#define CONFIG_UNIQUE_HISTORY   1   /* skip duplicate lines in scrollback */
#define CONFIG_ANSI_ARROWS      1   /* ANSI arrow key support */
#define CONFIG_EOF              1   /* Ctrl-D EOF */
#define CONFIG_SIGINT           1   /* Ctrl-C sends SIGINT */
#define CONFIG_SIGSTOP          1   /* Ctrl-Z sends SIGSTOP */
#define CONFIG_TERMINAL_BELL    1   /* bell on completion */

/* Do NOT use termcap - rely on termios directly */
/* #define CONFIG_USE_TERMCAP 1 */

#endif /* EDITLINE_CONFIG_H_ */
