# C++ Tests Master Makefile

.PHONY: all parser vm unit integration clean

all: parser vm unit integration

parser:
	@echo "=== Parser Tests ==="
	$(MAKE) -C parser test

vm:
	@echo "=== VM Tests ==="
	@echo "VM tests not yet implemented"
	# $(MAKE) -C vm test

unit:
	@echo "=== Unit Tests ==="
	@echo "Unit tests not yet implemented"
	# $(MAKE) -C unit test

integration:
	@echo "=== Integration Tests ==="
	@echo "Integration tests not yet implemented"
	# $(MAKE) -C integration test

clean:
	@echo "Cleaning C++ tests..."
	$(MAKE) -C parser clean
	# $(MAKE) -C vm clean
	# $(MAKE) -C unit clean
	# $(MAKE) -C integration clean
